services:
  web:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    ports:
      - "8080:80"
      - "5173:5173"
    volumes:
      - ./appRoot:/app
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/zz-custom.ini
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/app/public
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_sample_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  mysql_data:

networks:
  laravel_network:
    driver: bridge
